16 provide mapping UI for c8y hub events outbound
SoftwareAG/c8y-adamos-hub-connector pull request #32
Opened 2022-12-20 15:54 UTC by hnaether-sag

2022-12-20 17:52 UTC, hnaether-sag commented
Currently testing on pmt-training tenant. Conversion is working fine. Still todo is testing if flattening of attributes works.

2022-12-21 07:41 UTC, haraldmeyer requested changes
See comments.

2022-12-21 07:41 UTC, haraldmeyer commented on ax-mm-hubconnector/src/main/java/com/adamos/hubconnector/services/EventRulesService.java
> +	private Map<String, Date> lastUpdateDatesCache = new HashMap<>();
please use Instant instead of Date
https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html

2022-12-21 07:41 UTC, haraldmeyer commented on ax-mm-hubconnector/src/main/java/com/adamos/hubconnector/services/EventRulesService.java
> +	public void startListenersForEventMappings() {
I do not think this renaming is appropriate anymore as we decided to not start listeners.

2022-12-21 07:41 UTC, haraldmeyer commented on ax-mm-hubconnector/src/main/java/com/adamos/hubconnector/services/EventRulesService.java
> +	public void listenForMapping(EventMapping mapping, List<ManagedObjectRepresentation> selectedDevices) {
see comment above, we are not listening.

2022-12-21 07:41 UTC, haraldmeyer commented on ax-ui-hubconnector-microfrontend/ax-ui-hubconnector/shared/new-adamos-hub.service.ts
> +  ];
why hardcoded values here?

2022-12-21 12:43 UTC, haraldmeyer approved these changes

2022-12-21 13:37 UTC, merged